In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df = pd.read_excel(r"C:\Users\USER 01\Downloads\today.xlsx")

In [56]:
df.head()

,Client Employer,Number of Active Clients for Reporting Period,New Clients,Credit Income Earned (as per Income Statement),Loan Capital Amount,Total,Total Payable,Credits,Received,Arrears,Delinquency (Bad + Arrears),Delinquency (%),Unnamed: 12
0,CITY OF WINDHOEK,122,15,289544.19,953400,1242781.88,1295910.98,3.99,908563.87,382039.12,387343.12,29.889732,NaN
1,FIRST NATIONAL BANK OF NAMIBIA,76,5,274923.52,897950,1173551.52,1179868.52,0.00,1125288.51,54580.01,54580.01,4.625940,NaN
2,B2 GOLD NAMIBIA (PTY) LTD,72,10,249196.92,809200,1058792.92,996744.42,0.00,940093.09,56651.33,56651.33,5.683637,NaN
3,DUNDEE PRECIOUS METALS TSUMEB,77,8,240709.71,802250,1042899.90,1127821.02,0.00,812779.24,315041.78,315041.78,27.933668,NaN
4,GIPF/BENEFICIARIES,181,18,243613.70,799250,1043518.47,1019823.76,27.68,903378.62,116417.46,116417.46,11.415759,NaN

In [57]:
df.drop(columns=["Unnamed: 12"], inplace =True)

In [58]:
df.columns

Index(['Client Employer', 'Number of Active Clients for Reporting Period',
       'New Clients', 'Credit Income Earned (as per Income Statement)',
       'Loan Capital Amount', 'Total', 'Total Payable', 'Credits', 'Received',
       'Arrears', 'Delinquency (Bad + Arrears)', 'Delinquency (%)'],
      dtype='object')

In [59]:
df_group = df.groupby(["Number of Active Clients for Reporting Period"]).sum()

In [60]:
df_group["Delinquency (%)"] = df_group["Delinquency (Bad + Arrears)"]/(df_group["Total Payable"]-df_group["Credits"])*100

In [61]:
df_group.sort_values(by="Delinquency (%)", ascending=False)

,New Clients,Credit Income Earned (as per Income Statement),Loan Capital Amount,Total,Total Payable,Credits,Received,Arrears,Delinquency (Bad + Arrears),Delinquency (%)
Number of Active Clients for Reporting Period,,,,,,,,,,
123,20,43147.69,142920,185721.84,185035.22,0.68,113578.52,71456.02,71456.02,38.617666
167,8,136755.22,472840,609877.22,616576.55,0.66,392994.87,223581.02,223581.02,36.261720
325,22,114201.00,371300,486521.00,556416.50,0.00,360880.00,195536.50,195536.50,35.142110
106,8,82744.15,292730,375504.15,419937.10,0.00,283605.02,136332.08,136332.08,32.464881
37,9,35442.58,119410,154905.12,142505.12,0.00,98212.01,44293.11,44293.11,31.081767
111,40,250854.06,838120,1089748.76,1079130.07,0.01,754086.49,323743.57,325043.57,30.120889
122,15,289544.19,953400,1242781.88,1295910.98,3.99,908563.87,382039.12,387343.12,29.889732
172,17,138520.34,510780,649330.34,715266.42,0.00,505653.67,209612.75,209612.75,29.305549
48,6,114596.12,378800,493130.44,473430.86,4.57,338554.79,134871.50,134871.50,28.488384
16,0,32254.28,112200,144460.28,141450.82,0.00,102550.00,38900.82,38900.82,27.501304
23,1,30532.20,102700,133142.63,107271.08,0.00,78411.84,28859.24,28859.24,26.903094
96,20,40149.66,135800,176049.25,153971.41,0.00,113055.62,40915.79,40915.79,26.573628
59,4,79480.94,300190,379700.94,359391.59,0.00,264516.66,94874.93,94874.93,26.398762
77,16,272349.09,911450,1184027.28,1265221.02,0.00,933530.90,331690.12,331690.12,26.215982
57,7,80190.15,273500,353834.15,353371.12,0.01,261047.90,92323.21,92323.21,26.126417
25,6,78396.21,263250,341677.23,304918.40,0.00,227405.65,77512.75,77512.75,25.420818
34,8,83536.85,281890,365690.85,337413.82,0.00,254396.75,83017.07,83017.07,24.603933
33,1,34880.41,121960,157272.14,167033.03,0.00,126609.24,40423.79,40423.79,24.201076
246,36,98881.08,340890,440252.27,426183.58,0.34,336645.69,89537.55,89537.55,21.009167
41,21,86980.12,292320,379538.47,311889.69,0.00,248422.34,63467.35,63467.35,20.349294
80,26,293562.64,988131,1282168.44,1272873.39,0.34,1028866.91,241307.64,244006.14,19.169715
14,8,63527.06,210750,274404.72,228590.83,0.00,191772.46,36818.37,36818.37,16.106670
32,7,133708.58,461310,595168.58,608051.43,0.00,512628.77,93862.66,95422.66,15.693189
64,13,54955.71,198350,253328.56,281996.22,0.00,238719.88,43276.34,43276.34,15.346426
175,26,87609.96,297660,385268.83,402252.08,8.32,341151.10,61092.66,61092.66,15.187970
22,2,32985.24,107050,140293.24,133288.01,30.00,114166.37,19091.64,19091.64,14.326824
21,4,117390.49,404370,522012.49,534285.68,0.00,458124.00,76161.68,76161.68,14.254861
15,1,32632.65,106900,139580.65,136743.00,0.34,118568.32,18174.34,18174.34,13.290907
191,29,75488.19,247700,323728.19,292189.05,6.33,253632.84,38549.88,38549.88,13.193758
116,15,97031.22,323400,420815.22,427862.90,0.00,372214.57,55648.33,55648.33,13.006112
102,17,78718.74,273420,352558.74,354748.57,6.34,310622.89,44119.34,44119.34,12.437014
20,4,44365.16,141990,186529.16,155455.41,0.02,137645.39,17810.00,17810.00,11.456663
27,2,133347.26,447300,580031.59,564590.76,18.00,499929.62,64643.14,64643.14,11.449922
181,18,243613.70,799250,1043518.47,1019823.76,27.68,903378.62,116417.46,116417.46,11.415759
26,6,52033.05,170600,222729.05,194249.86,0.34,172700.09,21549.43,21549.43,11.093685
28,6,117214.48,386800,504314.48,508838.24,0.00,457326.46,51511.78,51511.78,10.123410
39,2,111116.18,375550,486894.18,471658.61,0.00,428245.53,43413.08,43413.08,9.204344
62,5,28544.26,108810,137450.26,198021.38,0.00,179900.36,18121.02,18121.02,9.151042
36,1,32975.27,111800,144853.27,140167.14,1.66,128812.14,11353.34,11353.34,8.099954
12,1,74953.54,243750,318901.54,277237.78,0.00,255987.11,21250.67,21250.67,7.665142
18,3,45875.13,156490,202503.13,210025.99,0.00,194319.32,15706.67,15706.67,7.478441
95,10,69473.57,231690,301403.57,328083.43,0.00,305049.08,23034.35,23034.35,7.020882
42,4,85050.90,287020,371734.22,360774.32,0.00,336590.73,24183.59,24183.59,6.703246
84,10,73637.73,250000,324111.73,306579.26,0.00,286147.59,20431.67,20431.67,6.664401
223,25,116356.81,400650,517774.81,541171.88,0.00,506625.31,34546.57,34546.57,6.383659
92,7,70657.50,229980,300887.04,297210.81,0.00,279275.51,17935.30,17935.30,6.034538
76,15,420033.81,1385650,1806757.81,1785245.72,0.00,1679736.56,105509.16,105509.16,5.910064
44,10,230049.58,787120,1017865.58,1001444.48,0.00,943296.98,58147.50,58147.50,5.806363
72,10,249196.92,809200,1058792.92,996744.42,0.00,940093.09,56651.33,56651.33,5.683637
55,5,159035.69,573030,732431.69,772703.84,0.01,729232.82,43471.01,43471.01,5.625831
120,9,152820.69,557600,710912.69,725326.34,0.00,686890.50,38435.84,38435.84,5.299110
35,3,75509.42,256650,332303.42,327702.35,0.00,311237.36,16464.99,16464.99,5.024373
45,7,231359.51,811980,1043939.51,1047039.58,0.00,1003422.93,43616.65,43616.65,4.165712
11,0,50737.75,172550,223401.75,188978.34,0.00,181698.34,7280.00,7280.00,3.852293
47,10,32181.69,104850,137151.69,99255.71,0.00,95832.37,3423.34,3423.34,3.449011
61,9,75245.44,245000,320437.44,279212.49,0.00,270620.66,8591.83,8591.83,3.077165
29,5,38115.09,127450,165745.09,154608.63,0.00,151111.13,3497.50,3497.50,2.262164
13,1,44852.61,145700,190678.61,136478.33,0.00,133483.33,2995.00,2995.00,2.194488
65,6,44845.66,146300,191475.66,212419.97,0.00,208779.97,3640.00,3640.00,1.713587
24,2,51006.36,181900,233056.36,240229.99,0.00,237417.49,2812.50,2812.50,1.170753

In [62]:
df1= df.astype({"Delinquency (%)":"int64"})

In [36]:
df1[df1["Delinquency (%)"]==68]

,Client Employer,Number of Active Clients for Reporting Period,New Clients,Credit Income Earned (as per Income Statement),Loan Capital Amount,Total,Total Payable,Credits,Arrears,Delinquency (Bad + Arrears),Delinquency (%)
141,ETN TECHNICAL SERVICES,9,2,7873.0,28050,35923.0,37179.66,0.0,25601.0,25601.0,68

In [63]:
df1.groupby(["Delinquency (%)","Client Employer"]).sum()

                                                           Number of Active Clients for Reporting Period  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY                                                    44
1               DE BEERS MARINE NAMIBIA (PTY) LTD                                                     27
                EMBWIINDA FISHING WAGES                                                               65
                SWAKOPMUND  MUNICIPALITY                                                              24
2               BOKOMO FOODS NAMIBIA (PTY) LTD                                                        29
...                                                                                                  ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD                                            325
                OSHANA SECURITY                                                                      111
36              MINISTRY OF WORKS AND TRANSPORT                                                      167
38              AFRICA PERSONNEL SERVICES                                                            123
                TRANSNAMIB HOLDING LTD.                                                              111

                                                           New Clients  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY                   4
1               DE BEERS MARINE NAMIBIA (PTY) LTD                    1
                EMBWIINDA FISHING WAGES                              6
                SWAKOPMUND  MUNICIPALITY                             2
2               BOKOMO FOODS NAMIBIA (PTY) LTD                       5
...                                                                ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD           22
                OSHANA SECURITY                                     13
36              MINISTRY OF WORKS AND TRANSPORT                      8
38              AFRICA PERSONNEL SERVICES                           20
                TRANSNAMIB HOLDING LTD.                             11

                                                           Credit Income Earned (as per Income Statement)  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY                                               60038.26
1               DE BEERS MARINE NAMIBIA (PTY) LTD                                                99240.23
                EMBWIINDA FISHING WAGES                                                          44845.66
                SWAKOPMUND  MUNICIPALITY                                                         51006.36
2               BOKOMO FOODS NAMIBIA (PTY) LTD                                                   38115.09
...                                                                                                   ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD                                       114201.00
                OSHANA SECURITY                                                                  56255.10
36              MINISTRY OF WORKS AND TRANSPORT                                                 136755.22
38              AFRICA PERSONNEL SERVICES                                                        43147.69
                TRANSNAMIB HOLDING LTD.                                                         127918.70

                                                           Loan Capital Amount  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY                      195570
1               DE BEERS MARINE NAMIBIA (PTY) LTD                       332150
                EMBWIINDA FISHING WAGES                                 146300
                SWAKOPMUND  MUNICIPALITY                                181900
2               BOKOMO FOODS NAMIBIA (PTY) LTD                          127450
...                                                                        ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD               371300
                OSHANA SECURITY                                         193920
36              MINISTRY OF WORKS AND TRANSPORT                         472840
38              AFRICA PERSONNEL SERVICES                               142920
                TRANSNAMIB HOLDING LTD.                                 429550

                                                               Total  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY         256034.26
1               DE BEERS MARINE NAMIBIA (PTY) LTD          431594.23
                EMBWIINDA FISHING WAGES                    191475.66
                SWAKOPMUND  MUNICIPALITY                   233056.36
2               BOKOMO FOODS NAMIBIA (PTY) LTD             165745.09
...                                                              ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD  486521.00
                OSHANA SECURITY                            250205.10
36              MINISTRY OF WORKS AND TRANSPORT            609877.22
38              AFRICA PERSONNEL SERVICES                  185721.84
                TRANSNAMIB HOLDING LTD.                    557655.40

                                                           Total Payable  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY             237417.63
1               DE BEERS MARINE NAMIBIA (PTY) LTD              398938.39
                EMBWIINDA FISHING WAGES                        212419.97
                SWAKOPMUND  MUNICIPALITY                       240229.99
2               BOKOMO FOODS NAMIBIA (PTY) LTD                 154608.63
...                                                                  ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD      556416.50
                OSHANA SECURITY                                244937.00
36              MINISTRY OF WORKS AND TRANSPORT                616576.55
38              AFRICA PERSONNEL SERVICES                      185035.22
                TRANSNAMIB HOLDING LTD.                        553391.89

                                                           Credits   Received  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY            0.00  235207.63
1               DE BEERS MARINE NAMIBIA (PTY) LTD            18.00  391748.72
                EMBWIINDA FISHING WAGES                       0.00  208779.97
                SWAKOPMUND  MUNICIPALITY                      0.00  237417.49
2               BOKOMO FOODS NAMIBIA (PTY) LTD                0.00  151111.13
...                                                            ...        ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD     0.00  360880.00
                OSHANA SECURITY                               0.00  158374.49
36              MINISTRY OF WORKS AND TRANSPORT               0.66  392994.87
38              AFRICA PERSONNEL SERVICES                     0.68  113578.52
                TRANSNAMIB HOLDING LTD.                       0.01  340164.14

                                                             Arrears  \
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY           2210.00
1               DE BEERS MARINE NAMIBIA (PTY) LTD            7171.67
                EMBWIINDA FISHING WAGES                      3640.00
                SWAKOPMUND  MUNICIPALITY                     2812.50
2               BOKOMO FOODS NAMIBIA (PTY) LTD               3497.50
...                                                              ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD  195536.50
                OSHANA SECURITY                             86562.51
36              MINISTRY OF WORKS AND TRANSPORT            223581.02
38              AFRICA PERSONNEL SERVICES                   71456.02
                TRANSNAMIB HOLDING LTD.                    213227.74

                                                           Delinquency (Bad + Arrears)
Delinquency (%) Client Employer
0               COCA-COLA NAMIBIA BOTTLING COMPANY                             2210.00
1               DE BEERS MARINE NAMIBIA (PTY) LTD                              7171.67
                EMBWIINDA FISHING WAGES                                        3640.00
                SWAKOPMUND  MUNICIPALITY                                       2812.50
2               BOKOMO FOODS NAMIBIA (PTY) LTD                                 3497.50
...                                                                                ...
35              OMEGA SECURITY SERVICES NAMIBIA (PTY) LTD                    195536.50
                OSHANA SECURITY                                               86562.51
36              MINISTRY OF WORKS AND TRANSPORT                              223581.02
38              AFRICA PERSONNEL SERVICES                                     71456.02
                TRANSNAMIB HOLDING LTD.                                      213227.74

[80 rows x 10 columns]

In [64]:
df

,Client Employer,Number of Active Clients for Reporting Period,New Clients,Credit Income Earned (as per Income Statement),Loan Capital Amount,Total,Total Payable,Credits,Received,Arrears,Delinquency (Bad + Arrears),Delinquency (%)
0,CITY OF WINDHOEK,122,15,289544.19,953400,1242781.88,1295910.98,3.99,908563.87,382039.12,387343.12,29.889732
1,FIRST NATIONAL BANK OF NAMIBIA,76,5,274923.52,897950,1173551.52,1179868.52,0.00,1125288.51,54580.01,54580.01,4.625940
2,B2 GOLD NAMIBIA (PTY) LTD,72,10,249196.92,809200,1058792.92,996744.42,0.00,940093.09,56651.33,56651.33,5.683637
3,DUNDEE PRECIOUS METALS TSUMEB,77,8,240709.71,802250,1042899.90,1127821.02,0.00,812779.24,315041.78,315041.78,27.933668
4,GIPF/BENEFICIARIES,181,18,243613.70,799250,1043518.47,1019823.76,27.68,903378.62,116417.46,116417.46,11.415759
...,...,...,...,...,...,...,...,...,...,...,...,...
75,KAVANGO EAST REGIONAL COUNCIL,21,0,26024.00,105170,131194.00,140837.34,0.00,109154.01,31683.33,31683.33,22.496399
76,SEAFLOWER WHITEFISH,47,10,32181.69,104850,137151.69,99255.71,0.00,95832.37,3423.34,3423.34,3.449011
77,PUPKEWITZ MOTORS,23,1,30532.20,102700,133142.63,107271.08,0.00,78411.84,28859.24,28859.24,26.903094
78,QKR NAMIBIA NAVACHAB GOLD MINE,14,6,30676.19,100750,131451.85,88392.81,0.00,61674.48,26718.33,26718.33,30.226814
79,ONGWEDIVA MEDIPARK,28,3,30393.01,100100,130583.01,124758.37,0.00,103698.36,21060.01,21060.01,16.880639

In [67]:
df1.groupby(["Delinquency (%)","Client Employer"]).sum().to_excel(r"C:\Users\USER 01\Downloads\deliquency_employer.xlsx")

In [65]:
df1_groupby = df1.groupby(["Delinquency (%)"]).sum()

In [68]:
df1_groupby.to_excel(r"C:\Users\USER 01\Downloads\deliquency.xlsx")

In [66]:
df1_groupby

,Number of Active Clients for Reporting Period,New Clients,Credit Income Earned (as per Income Statement),Loan Capital Amount,Total,Total Payable,Credits,Received,Arrears,Delinquency (Bad + Arrears)
Delinquency (%),,,,,,,,,,
0,44,4,60038.26,195570,256034.26,237417.63,0.00,235207.63,2210.00,2210.00
1,116,9,195092.25,660350,856126.25,851588.35,18.00,837946.18,13624.17,13624.17
2,122,16,124487.35,416960,542197.35,473371.91,0.00,462210.25,11161.66,11161.66
3,176,23,261963.79,904980,1167759.79,1045603.62,0.00,1010661.13,34942.49,34942.49
4,149,10,491354.76,1618750,2111184.76,2113687.56,0.00,2016604.23,97083.33,97083.33
5,282,27,636562.72,2196480,2834440.72,2822476.95,0.01,2667453.77,155023.17,155023.17
6,441,46,345702.94,1167650,1514507.80,1505736.27,0.00,1408639.14,97097.13,97097.13
7,192,22,357042.61,1216280,1574174.61,1625829.31,0.00,1506425.73,119403.58,119403.58
8,303,31,324478.20,1080550,1406300.20,1358656.14,1.66,1241763.65,115590.83,116890.83
9,135,9,172798.53,593760,767092.53,794248.58,0.00,721426.14,72822.44,72822.44
10,32,4,95732.58,324010,419892.58,440922.11,0.00,396372.77,42989.34,44549.34
11,227,28,340011.91,1111840,1452776.68,1369529.03,28.04,1213724.10,155776.89,155776.89
12,219,27,183262.49,621670,805856.49,788529.68,6.34,690587.21,97936.13,97936.13
13,322,45,205152.06,678000,884124.06,856794.95,6.67,744415.73,112372.55,112372.55
14,43,5,85520.01,279700,365628.01,343241.33,30.00,294266.36,48944.97,48944.97
15,239,39,142565.67,496010,638597.39,684248.30,8.32,579870.98,104369.00,104369.00
16,28,3,30393.01,100100,130583.01,124758.37,0.00,103698.36,21060.01,21060.01
19,41,4,37247.09,130700,168047.44,209825.51,0.00,168512.82,41312.69,41312.69
21,287,53,148614.11,502510,651743.30,528247.76,0.34,416555.21,111692.21,111692.21
22,46,5,72410.52,259470,331910.52,317663.73,0.00,246696.01,70967.72,70967.72
24,33,1,34880.41,121960,157272.14,167033.03,0.00,126609.24,40423.79,40423.79
26,235,32,230352.95,812190,1042726.97,974005.20,0.01,717032.02,256973.17,256973.17
27,173,16,372320.05,1249520,1621409.04,1697558.40,0.00,1227013.74,467846.16,470544.66
28,128,10,187570.67,621651,809123.99,803422.12,4.91,575165.81,228251.40,228251.40
29,319,33,460074.22,1573130,2033072.93,2139269.41,3.99,1504081.19,629880.23,635184.23
30,46,9,68652.19,238050,306727.85,255522.13,0.00,177930.48,77591.65,77591.65
31,37,9,35442.58,119410,154905.12,142505.12,0.00,98212.01,44293.11,44293.11
32,106,8,82744.15,292730,375504.15,419937.10,0.00,283605.02,136332.08,136332.08
33,34,6,50398.76,172490,222942.76,212845.23,0.00,141116.50,71728.73,71728.73
34,27,1,34107.03,115150,148437.36,165652.37,0.00,108180.90,57471.47,57471.47
35,436,35,170456.10,565220,736726.10,801353.50,0.00,519254.49,282099.01,282099.01
36,167,8,136755.22,472840,609877.22,616576.55,0.66,392994.87,223581.02,223581.02
38,234,31,171066.39,572470,743377.24,738427.11,0.69,453742.66,284683.76,284683.76